name: flutter_map_picker
description: This package allows you to pick a point, a circle or a custom area in Google Maps
version: 0.1.3
author: Luis Barba <lymtechx@gmail.com>
homepage: https://lymtechx.com/
repository: https://github.com/lymtechx/flutter_map_picker
issue_tracker: https://github.com/lymtechx/flutter_map_picker/issues

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_google_places: ^0.3.0
  google_maps_flutter: ^2.2.5
  google_maps_utils: ^1.5.0+0
  location: ^5.0.0-dev.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
